version: '3.8'

services:
  db:
    image: postgres:15
    container_name: forum_pg
    restart: always
    environment:
      POSTGRES_USER: forum_user
      POSTGRES_PASSWORD: forum_pass
      POSTGRES_DB: forum_logs
    ports:
      - "5432:5432"
    volumes:
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
